targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options for json_serializable
          any_map: false
          checked: true
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true

# Web build optimizations
global_options:
  flutter_web:
    options:
      # Enable tree shaking for smaller bundle sizes
      tree_shake_icons: true
      # Split debug info for better performance
      split_debug_info: true
      # Enable source maps for debugging
      source_maps: true
      # Optimize for web performance
      web_renderer: canvaskit
      # Enable deferred loading
      deferred_loading: true 