name: time
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.3.8
  
  # Supabase
  supabase_flutter: ^2.8.0
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  
  # Navigation
  go_router: ^14.6.2
  
  # Forms
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  
  # File & Image Handling
  file_picker: ^8.1.4
  cached_network_image: ^3.4.1
  image_picker_web: ^3.0.0
  
  # HTTP requests
  http: ^1.2.2
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  timeago: ^3.7.0
  csv: ^6.0.0
  path: ^1.9.0
  crypto: ^3.0.5
  
  # UI
  cupertino_icons: ^1.0.8
  
  # Code Generation Support
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  logger: ^2.4.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  pdf: ^3.11.3
  syncfusion_flutter_pdfviewer: ^30.1.39
  universal_html: ^2.2.4
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2
  
  # Testing
  mockito: ^5.4.4
  fake_cloud_firestore: ^3.0.3

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/ 
    - assets/fonts/Roboto-Regular.ttf 
    - assets/fonts/Roboto-Bold.ttf 
    - assets/fonts/NotoSans-Regular.ttf
    - assets/fonts/NotoSans-Bold.ttf 